[pytest]
# --- 📌 优化点：设置默认参数，自动生成数据并清理旧数据 ---
addopts = --alluredir=./allure-results --clean-alluredir

# 开启实时日志显示
log_cli = true
# 设置显示的最低级别 (INFO, DEBUG, WARNING, ERROR)
log_cli_level = INFO
# 设置日志格式
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
# 设置时间格式
log_cli_date_format = %Y-%m-%d %H:%M:%S
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning