[pytest]
# 开启实时日志显示
log_cli = true
# 设置显示的最低级别 (INFO, DEBUG, WARNING, ERROR)
log_cli_level = INFO
# 设置日志格式 (跟我们在 Python 代码里写的一样，但这里是全局配置)
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
# 设置时间格式
log_cli_date_format = %Y-%m-%d %H:%M:%S
# 👇 新增下面这几行，屏蔽 urllib3 的安全警告
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning